"""Stage and scan actual source inputs using installed fdroidserver (no APK build).

Run after prepare_native.py and build_sherpa.py --sources-only, with fdroidserver
installed in a dedicated environment. Copy inputs because the scanner may delete
unneeded files listed in scandelete. Never scan/mutate another worktree or caches.
The metadata uses a synthetic SHA only for local syntax/lint checking; submission
metadata must be generated by fdroid_metadata.py from the actual release commit.
"""
import argparse
import os
import pathlib
import shutil
import subprocess
import sys
import types
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[2]


class FdroidCheck:
    def run(self, destination):
        from fdroidserver import common, metadata, scanner
        if destination.exists():
            raise ValueError("Use a fresh staging directory to preserve previous evidence")
        source = destination / "source"
        source.mkdir(parents=True)
        files = subprocess.check_output(["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"], cwd=ROOT).decode().split("\0")
        for name in files:
            original = ROOT / name
            if name and original.is_file():
                target = source / name
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(original, target)
        for name in ("crispasr", "sherpa-onnx", "sherpa-deps", "onnxruntime-notices"):
            shutil.copytree(ROOT / ".native-cache" / name, source / ".native-cache" / name,
                            ignore=shutil.ignore_patterns(".git", "__pycache__"), symlinks=True)
        subprocess.run([sys.executable, str(source / "tools/prepare_fdroid.py")], check=True)
        metadata_dir = destination / "metadata"
        metadata_dir.mkdir()
        template = (ROOT / "docs/distribution/fdroid/io.github.lrq3000.utterlane.yml.in").read_text(encoding="utf-8")
        recipe = metadata_dir / "io.github.lrq3000.utterlane.yml"
        recipe.write_text(template.replace("@RELEASE_COMMIT@", "0" * 40), encoding="utf-8")
        # Use the repository's current taxonomy, not fdroidserver's older built-in
        # fallback categories. This public config is evidence, not app source.
        config = destination / "config"
        config.mkdir()
        with urllib.request.urlopen("https://gitlab.com/fdroid/fdroiddata/-/raw/master/config/categories.yml", timeout=30) as response:
            from ruamel.yaml import YAML
            yaml = YAML()
            categories = yaml.load(response.read().decode("utf-8"))
            # Lint needs the official taxonomy, not the repository's icon files.
            for details in categories.values():
                details.pop("icon", None)
            with (config / "categories.yml").open("w", encoding="utf-8") as output:
                yaml.dump(categories, output)
        os.chdir(destination)
        common.options = types.SimpleNamespace(verbose=False, quiet=False)
        common.config = common.read_config()
        scanner.config = common.config
        scanner.options = types.SimpleNamespace(json=False, refresh_scanner=False)
        app = metadata.parse_metadata(recipe)
        errors = scanner.scan_source(str(source), app.Builds[0])
        print(f"F-Droid source scan: {errors} errors; staged at {destination}")
        if errors:
            raise SystemExit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    FdroidCheck().run(parser.parse_args().output.resolve())
